name: Bug report
description: Report a reproducible defect.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Include exact commands or UI steps.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, branch/commit.
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Logs or screenshots
      description: Paste relevant output.
    validations:
      required: false

