name: Feature or task
description: Propose implementation work with clear acceptance criteria.
title: "[Task] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe scope and approach.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: List objective criteria for completion.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies and constraints
      description: Upstream/downstream constraints, blocked items, external dependencies.
    validations:
      required: false

